[package]
name = "surviving_async"
version = "0.1.0"
authors = ["michael wagner <michael.wagner@tum-create.edu.sg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.3"
sha3 = "0.9.1"
color-eyre ="0.5.1"
