# Check https://rust-lang.github.io/rustup-components-history/ for
# latest nightly availability of rls and rustfmt.

# Reference: https://rust-lang.github.io/rustfmt/

# merge_imports = true
comment_width = 100
normalize_comments = true
wrap_comments = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
reorder_impl_items = true
format_code_in_doc_comments = true